export const C = {
  bg: "#090C12",
  surface: "#0F1520",
  card: "#131B2A",
  border: "#1E2D45",
  accent: "#00D4FF",
  accentGlow: "#00D4FF33",
  gold: "#FFB800",
  green: "#00E88F",
  red: "#FF4757",
  purple: "#8B5CF6",
  text: "#E8F0FE",
  muted: "#6B7E9F",
  orange: "#FF9500",
  pink: "#FF6B9D",
};

export const MODULES = [
  { id: "jobs",     icon: "🔎", label: "Job Search",      color: C.green    },
  { id: "scan",     icon: "⚡", label: "Resume Scan",     color: C.accent   },
  { id: "ats",      icon: "✨", label: "ATS Builder",     color: C.purple   },
  { id: "jd",       icon: "🔍", label: "JD Analyzer",     color: C.pink     },
  { id: "star",     icon: "⭐", label: "STAR Builder",     color: C.gold     },
  { id: "simulate", icon: "🧠", label: "HM Simulator",    color: C.purple   },
  { id: "salary",   icon: "💰", label: "Salary Coach",    color: C.green    },
  { id: "cover",    icon: "✉️", label: "Cover Letter",   color: C.orange   },
  { id: "radar",    icon: "📡", label: "Weakness Radar",  color: C.red      },
  { id: "score",    icon: "🏆", label: "Readiness Score", color: C.accent   },
  { id: "market",   icon: "🌏", label: "Market Intel",    color: C.muted    },
  { id: "memory",   icon: "🧬", label: "AI Memory",        color: C.purple   },
  { id: "culture",  icon: "🧭", label: "Culture Quiz",     color: C.accent   },
];
