export const C = {
  bg: "#090C12",
  surface: "#0F1520",
  card: "#131B2A",
  border: "#1E2D45",
  accent: "#EC4899",
  accentGlow: "#EC489933",
  gold: "#FFB800",
  green: "#00E88F",
  red: "#FF4757",
  purple: "#8B5CF6",
  text: "#E8F0FE",
  muted: "#6B7E9F",
  orange: "#FF9500",
  pink: "#FF6B9D",
};

export const MODULES = [
  { id: "dashboard",  icon: "⚡", label: "Dashboard",        color: C.accent   },
  { id: "scan",       icon: "⚡", label: "ATS Scanner",      color: C.accent   },
  { id: "ats",        icon: "📄", label: "Resume Builder",   color: C.purple   },
  { id: "cover",      icon: "✉️", label: "Cover Letter AI", color: C.orange   },
  { id: "simulate",   icon: "🧠", label: "Interview Coach",  color: C.purple   },
  { id: "salary",     icon: "💰", label: "Salary Prep",      color: C.green    },
  { id: "skillsgap",  icon: "📊", label: "Skills Gap",       color: C.pink     },
  { id: "roadmap",    icon: "🗺️", label: "Career Roadmap",   color: C.purple   },
  { id: "verify",     icon: "🛡️", label: "Verify Creds",     color: C.gold     },
  { id: "trustmatch", icon: "🤝", label: "TrustMatch",       color: C.purple   },
  { id: "aichat",     icon: "🤖", label: "AI Career Coach",  color: C.green    },
  { id: "culture",    icon: "🧭", label: "Culture Quiz",     color: C.accent   },
  // kept for internal navigation (not in sidebar)
  { id: "jobs",     icon: "🔎", label: "Job Search",      color: C.green    },
  { id: "jd",       icon: "🔍", label: "JD Analyzer",     color: C.pink     },
  { id: "star",     icon: "⭐", label: "STAR Builder",     color: C.gold     },
  { id: "radar",    icon: "📡", label: "Weakness Radar",   color: C.red      },
  { id: "score",    icon: "🏆", label: "Readiness Score",  color: C.accent   },
  { id: "market",   icon: "🌏", label: "Market Intel",     color: C.muted    },
  { id: "memory",   icon: "🧬", label: "AI Memory",        color: C.purple   },
];
